# Generated by Django 4.0.3 on 2022-03-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='calories',
            new_name='calories_in_100g',
        ),
    ]
